version: '3'
services:
  coolblue_cart_mysql:
    image: mysql:5.7
    platform: linux/x86_64
    container_name: coolblue_cart_mysql
    environment:
      MYSQL_DATABASE: 'coolblue'
      MYSQL_USER: 'interview'
      MYSQL_PASSWORD: 'interview'
      MYSQL_ROOT_PASSWORD: 'secretrootpassword'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - ./etc:/docker-entrypoint-initdb.d/:ro

  coolblue_cart_php:
    container_name: coolblue_cart_php
    build:
      dockerfile: ./docker/php/Dockerfile
    volumes:
      - ./:/app
    ports:
      - '9000:9000'

  coolblue_cart_composer:
    image: composer:latest
    container_name: coolblue_cart_composer
    command: composer install --ignore-platform-reqs
    volumes:
      - ./:/app

  coolblue_cart_nginx:
    image: nginx:alpine
    container_name: coolblue_cart_nginx
    volumes:
      - ./:/app
      - ./docker/nginx/site.conf:/etc/nginx/conf.d/default.conf
    ports:
      - '8080:80'
    links:
      - coolblue_cart_php
